export const ADD_TO_BLACK_LIST = 'ADD_TO_BLACK_LIST';
export const DELETE_FROM_BLACK_LIST = 'DELETE_FROM_BLACK_LIST';

export const GET_REVIEWER__REQUEST = 'GET_REVIEWER__REQUEST';
export const GET_REVIEWER__SUCCESS = 'GET_REVIEWER__SUCCESS';
export const GET_REVIEWER__FAILURE = 'GET_REVIEWER__SUCCESS';

export const UPDATE__FROM_LS = 'UPDATE__FROM_LS'